package com.linda.rpc.webui.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.linda.rpc.webui.pojo.AppInfo;

/**
 * @author AutoGenerated by lindzh
 * 2016年12月15日 16:52
 */
public interface AppInfoDao {

	public int addAppInfo(AppInfo obj);

	public AppInfo getById(@Param("id")long id);
	
	public int updateById(@Param("obj")AppInfo obj);
	
	public int deleteById(@Param("id")long id);
	
	
	public List<AppInfo> getListByAppName(@Param("name")String name,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByAppName(@Param("name")String name);
	
}
