package com.linda.rpc.webui.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.linda.rpc.webui.pojo.ServiceProviderInfo;

/**
 * @author AutoGenerated by lindzh
 * 2016年12月15日 16:55
 */
public interface ServiceProviderInfoDao {

	public int addServiceProviderInfo(ServiceProviderInfo obj);

	public ServiceProviderInfo getById(@Param("id")long id);
	
	public int updateById(@Param("obj")ServiceProviderInfo obj);
	
	public int deleteById(@Param("id")long id);

	public int deleteByAppIdAndHostId(long appId,long hostId);

	public ServiceProviderInfo getByAppHostAndServiceId(long appId,long hostId,long serviceId);

	public int getServiceProviderCount(long appId,long ServiceId);
	
}
