package com.linda.rpc.webui.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.linda.rpc.webui.pojo.ServiceInfo;

/**
 * @author AutoGenerated by lindzh
 * 2016年12月15日 16:55
 */
public interface ServiceInfoDao {

	public int addServiceInfo(ServiceInfo obj);

	public ServiceInfo getById(@Param("id")long id);
	
	public int updateById(@Param("obj")ServiceInfo obj);
	
	public int deleteById(@Param("id")long id);
	
	
	public List<ServiceInfo> getListByServiceName(@Param("name")String name,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByServiceName(@Param("name")String name);
	
	
	public List<ServiceInfo> getListByAppIdAndStatus(@Param("appId")long appId,@Param("status")int status,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByAppIdAndStatus(@Param("appId")long appId,@Param("status")int status);
	
}
